########################################################################
## Travis CI config for QChartSynZoom
##
## Steps:
## * installs '3rdparty' from source
## * confirms build and install
########################################################################

sudo: required
dist: trusty

language: cpp
compiler: gcc

env:
  global:
    - INSTALL_PREFIX=/tmp

    # Speeding up build??!
    # https://docs.travis-ci.com/user/speeding-up-the-build/
    # https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
    - MAKEFLAGS="-j 2"

    - QT_SELECT=4
    - USE_QWT=local

  matrix:
    # Testing under Ubuntu-Trusty system libraries
    - USE_QWT=systm   QT_SELECT=4
    - USE_QWT=systm   QT_SELECT=5

    # Qwt versions < 5.2 are not supported??!!
    #- QWT_VERSION=tags/qwt-5.0.0
    #- QWT_VERSION=tags/qwt-5.0.1
    #- QWT_VERSION=qwt-5.0

    #- QWT_VERSION=tags/qwt-5.1.0
    #- QWT_VERSION=tags/qwt-5.1.1
    #- QWT_VERSION=qwt-5.1

    - QWT_VERSION=tags/qwt-5.2.1
    - QWT_VERSION=tags/qwt-5.2.2
    - QWT_VERSION=tags/qwt-5.2.3
    - QWT_VERSION=qwt-5.2
    - QWT_VERSION=tags/qwt-6.0.1
    - QWT_VERSION=tags/qwt-6.0.2
    - QWT_VERSION=qwt-6.0

    - QWT_VERSION=tags/qwt-6.1.0
    - QWT_VERSION=tags/qwt-6.1.1
    - QWT_VERSION=tags/qwt-6.1.2
    - QWT_VERSION=tags/qwt-6.1.3
    - QWT_VERSION=qwt-6.1

    # Additional builds under Qt-5 environment
    - QWT_VERSION=tags/qwt-6.1.0   QT_SELECT=5
    - QWT_VERSION=tags/qwt-6.1.1   QT_SELECT=5
    - QWT_VERSION=tags/qwt-6.1.2   QT_SELECT=5
    - QWT_VERSION=tags/qwt-6.1.3   QT_SELECT=5
    - QWT_VERSION=qwt-6.1          QT_SELECT=5

    # Additional build for future versios: Qwt-6.2.0 + Qt-5
    - QWT_VERSION=qwt-6.2          QT_SELECT=4
    - QWT_VERSION=qwt-6.2          QT_SELECT=5

before_install:
  # regular ubuntu packages
  - sudo add-apt-repository main
  - sudo add-apt-repository universe

  # update after package changes
  - sudo apt-get -qq update

  # Check avaliable versions of Qwt (on Trusty)
  #- sudo apt-cache search libqwt
  #- sudo apt-cache search qtsvg
  #- sudo apt-cache search qt

install:
  # Qt development files
  - sudo apt-get -qq update
  - sudo apt-get install -qq -y libqt4-dev qtbase5-dev qtchooser
  - sudo apt-get install -qq -y libqt4-svg
  - sudo apt-get install -qq -y libqt5svg5 libqt5svg5-dev
  - sudo apt-get install -qq -y libqt4-designer qt4-designer
  - sudo apt-get install -qq -y libqt5designer5 libqt5designercomponents5
  - sudo apt-get install -qq -y qttools5-dev qttools5-dev-tools

  # Requirements for Qwt building from source (qwt packages avaliable on Trusty)
  - if [ "x$QT_SELECT" == "x4"  -a  "x$USE_QWT" != "xlocal" ] ; then
       sudo apt-get install -qq -y libqwt5-qt4 libqwt5-qt4-dev ;

       ls -la /usr/include/qwt* ;
       ls -la /usr/lib/libqw* ;

       if [ -e /usr/include/qwt-qt4/qwt_global.h ] ; then cat /usr/include/qwt-qt4/qwt_global.h | grep QWT_VERSION ; fi ;
    fi

  - if [ "x$QT_SELECT" == "x5"  -a  "x$USE_QWT" != "xlocal" ] ; then
       sudo apt-get install -qq -y libqwt6 libqwt-dev ;

       ls -la /usr/include/qwt* ;
       ls -la /usr/lib/libqw* ;

       if [ -e /usr/include/qwt/qwt_global.h ] ; then cat /usr/include/qwt/qwt_global.h | grep QWT_VERSION ; fi ;
    fi

before_script:
  - pushd 3rdparty
  - if [ "x${QWT_VERSION}" != "x" ] ; then
       git clone https://github.com/osakared/qwt.git -b ${QWT_VERSION} ;
    fi
  - ls -la

  - if [ -e qwt     ] ; then ls -la qwt     ; fi
  - if [ -e qwt/qwt ] ; then ls -la qwt/qwt ; fi

  - if [ -e qwt/qwt ] ; then echo "Qwt in subQwt, so trying to correct."; cp -frn qwt/qwt . ; rm -rf qwt/qwt ; fi

  - if [ -e qwt     ] ; then ls -la qwt     ; fi
  - if [ -e qwt/qwt ] ; then ls -la qwt/qwt ; fi

  - popd

script:
  - ./configure -library
  - qmake && make
  - ls -la
  - ls -la buildlib
  - ls -la lib

after_script:
  - make distclean

after_success:
  - echo "Success... Hooray!!!"

after_failure:
  - echo "Failure..."
